server:
  port: 8081

spring:
  application:
    name: product-service

  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/targul/protocol/openid-connect/certs
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
            redirect-uri: "http://localhost:8081/login/oauth2/code/github"
            client-name: GitHub
            authorization-grant-type: authorization_code
            provider: github
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
#  data:
#    redis:
#      url: ${DB_REDIS_URL}
#      password: ${DB_REDIS_PASSWORD}

  liquibase:
    enabled: true
    change-log: liquibase/changelog.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_POSTGRES_URL}
    username: ${DB_POSTGRES_USERNAME}
    password: ${DB_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    #    defer-datasource-initialization: true

application:
  feature:
    toggles:
      exampleToggle: true
