spring:
  application:
    name: product-service
  profiles:
    active: fakeRepository

application:
  feature:
    cosmoCats:
      enabled: false
    kittyProducts:
      enabled: false
    currencyRates:
      enabled: false