server:
  port: 8081

spring:
  application:
    name: product-service

  profiles:
    active: dev

  liquibase:
    enabled: true
    change-log: liquibase/changelog.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_POSTGRES_URL}
    username: ${DB_POSTGRES_USERNAME}
    password: ${DB_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    #    defer-datasource-initialization: true

application:
  feature:
    toggles:
      exampleToggle: true
