spring:
  application:
    name: product-service
  config:
    import: "optional:file:.env.properties"

  datasource:
    url: jdbc:postgresql://localhost:5432/productservicedb
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
